name: Go CLI CI

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/ci-cli.yaml
      - cli/**
      - sdk/go/**
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/ci-cli.yaml
      - cli/**
      - sdk/go/**
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: cli/go.mod

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.10.1
          working-directory: cli

      - name: Check licenses
        working-directory: cli
        run: make check-licenses

      - name: Check NOTICE
        working-directory: cli
        run: make check-notice

  test:
    name: Test
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: cli/go.mod

      - name: Test
        working-directory: cli
        run: make test

      - name: Build
        working-directory: cli
        run: make build
